CREATE TABLE dept(
	deptno INT,
	dname VARCHAR(30),
	city VARCHAR(30)
);

CREATE TABLE emp(
	empno INT,
	ename VARCHAR(20),
	job VARCHAR(10),
	hire_date DATE,
	sal INT,
	deptno INT,
	sex ENUM('m','f'),
	email VARCHAR(20)
);

ALTER TABLE dept MODIFY COLUMN deptno INT NOT NULL;
ALTER TABLE emp MODIFY COLUMN empno INT NOT NULL;
ALTER TABLE emp MODIFY COLUMN ename VARCHAR(20) NOT NULL;

ALTER TABLE dept ADD CONSTRAINT dname_uq UNIQUE(dname);

ALTER TABLE emp ADD CONSTRAINT email_uq UNIQUE(email);

ALTER TABLE dept ADD CONSTRAINT pk_deptno PRIMARY KEY(deptno);
ALTER TABLE dept MODIFY COLUMN deptno INT AUTO_INCREMENT;

ALTER TABLE emp ADD CONSTRAINT pk_empno PRIMARY KEY(empno);
ALTER TABLE emp MODIFY COLUMN empno INT AUTO_INCREMENT;

ALTER TABLE emp ADD CONSTRAINT fk_deptno FOREIGN KEY(deptno) REFERENCES dept(deptno) ON DELETE SET NULL;

ALTER TABLE emp ADD CONSTRAINT ck_sal CHECK(sal>1000);